spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: uname
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  

#above initialize-schema: means whatever tables r requird to launch this job, those tables will b reated in db      
  batch:
    jdbc:
      initialize-schema: always

#disable job run at startup      
    job:
      enabled: false
      

